version: '3.8'

services:
  app:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      - TG__TOKEN=${TG__TOKEN}
      - PG__URL=${TG__URL}
      - REDIS__URL=${TG__URL}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: