version: '3.8'

services:
  app:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      - TEST=postgres://postgres:password@db:5432/mydb