version: '3.8'

services:
  app:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      - TEST=${TEST}


  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: