name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_PROJECT_DIR }}/med_bot
            git pull origin main
          
            export TG__TOKEN=${{ secrets.TG__TOKEN }}
            export PG__URL=${{ secrets.PG__URL }}
            export REDIS__URL=${{ secrets.REDIS__URL }}
          
            docker compose down
          
            docker images --filter "dangling=true" -q | xargs -r docker rmi
          
            docker compose up -d --build